### ISSUE TITLE
Can we use OpenSearch as a drop in replacement for ElasticSearch for mod-search

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#1]
It would be really really nice to take advantage of a search-as-service option instead of hosting this in our cluster.

It seems like it should be possible. mod-search just wants a URL to your ES cluster and AWS OpenSearch is basically a clone of ES.

The only thing that worries me are the [plugins](https://www.elastic.co/guide/en/elasticsearch/plugins/7.15/analysis.html) that FOLIO mod-search [uses](https://github.com/folio-org/mod-search/blob/master/docker/elasticsearch/Dockerfile).

I'm not able to see exact equivalents in OpenSearch. However, mod-search may not use these plugins directly and the hope is that mod-search will "just work" by specifying the OpenSearch url.

Modules that use elasticsearch

```
mod-search
```

**Comment by jwfuller** [comment]
Taking a look at trying to get it running using a manual [Bitnami Helm Chart for v7.11](https://github.com/elastic/helm-charts/tree/7.11/elasticsearch). Used 7.11 version because that is before the license change.

- Manually remove all elasticsearch resources in Rancher: Workloads, Services, Persistent Volume Claims, Secrets, Namespaces
```
$ helm repo add bitnami https://charts.bitnami.com/bitnami
$ helm install elasticsearch -n elasticsearch-iris --set master.replicas=3,coordinating.service.type=LoadBalancer,plugins="analysis-icu;analysis-kuromoji;analysis-smartcn;analysis-nori;analysis-phonetic" bitnami/elasticsearch
```

**Comment by steveellis** [comment]
@jwfuller Do you remember the outcome of your work on deploying elastic via helm above? Did deploying and indexing elasticsearch via helm _ever_ work? Also it seems like maybe we conflated two things in this ticket: debugging and deploying elasticsearch in general vs deploying and getting opensearch to work at all. I think elasticsearch did work at least partially at one time in the iris deployment, but over time, not so much. And opensearch never worked.

Not saying that either one won't work or that one is better than the other, just gathering info.

**Comment by sabetiv** [comment]
Issue is no longer valid as we are now 3rd party hosted
