### ISSUE TITLE
Implement RBAC for pulumi cluster

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#103]
Currently the pulumi stack deploy code is tightly bound to the user that runs it. So if you create the cluster, you can grab the kubeconfg and get access. However other developers, even though they have the pulumi token, can't connect. The theory is that this is because we need to configure RBAC for the cluster.

[This blog post](https://www.pulumi.com/blog/simplify-kubernetes-rbac-in-amazon-eks-with-open-source-pulumi-packages/) provides the general approach. This is linked out of the crosswalk docs.

Here is the source that is referenced in the blog post. I think of special interest is the [use of groups](https://gist.github.com/d-nishi/ab462ea779e0615f29e8cfbb668272d7#file-index-ts-L62). We have a group ARN that we would like to use.

**Comment by steveellis** [comment]
This explains in greater detail exactly what is going on in the `createIAMRole` function of the code linked above: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html

Basically the thing that binds the authorization back to either 1) our whole account if we use the account ARN, or 2) the ART of individual users if we want to go that route is `Principal`.

**Comment by steveellis** [comment]
These two docs have been very useful:
* https://aws.amazon.com/premiumsupport/knowledge-center/iam-assume-role-cli/
* https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access

The role that we have created in code gives users in our account the ability to assume the role. The [latest commit](https://github.com/culibraries/folio/commit/c78a5116de6a52f5de621b96f1ee5796c16a93b8.) has instructions in the readme for how to do this. I have tested it and it works for me. After assuming the role, my aws tokens are overridden and I'm able to connect to the cluster with the tokens provided after assuming the role.

**Comment by steveellis** [comment]
@jwfuller I'm going to argue that we consider pulumi operations and accessing the cluster two different things, each with their own methods of access.

Here's the problem we're trying to solve: we have to assume a role to access the cluster. This is known. Why not just have that role have the access it needs to do pulumi stuff too. Seems reasonable. One login for everything.

The problem is that the kind of access we need to do pulumi stuff is quite a bit different from the kind of access we need to login to the cluster. In fact, after some experimentation, it's pretty clear that the pulumi stuff needs _a lot more access_ to do its work than we need to access the cluster.

The upshot of this is that the role that we have to access the cluster is missing all sorts of stuff to do the pulumi stuff. We could try to add these permissions into the pulumi code, but every time you need to do a new thing like create a new resource, you'll have to log back out of the role and log back in with your default creds, run `pulumi up` there, and try it out back in the assumed mode -- switching back and forth until you have it right. A lot more unpleasant than staying in pulumi's more friendly god mode for pulumi stuff.

Here are some examples of the kinds of errors I saw trying to run pulumi under the assumed role:

![image](https://user-images.githubusercontent.com/104455/142507193-64f54fd2-945f-4698-882e-715e0b85bf5a.png)

![image](https://user-images.githubusercontent.com/104455/142507251-78f9467b-e79a-4c51-9550-0dbbaad118e3.png)

Assuming the role is a pain, but there are a lot of clever scripts out there to do it in a one liner [like this](https://stackoverflow.com/questions/63241009/aws-sts-assume-role-in-one-command) for example. And then another one liner to switch back out.

**Comment by jwfuller** [comment]
@steveellis This seems reasonable

**Comment by steveellis** [comment]
@jwfuller Cool, thanks. Let me clean up my code and abstract everything out into submodules (haven't done that yet) and then I'll open a PR (hopefully this afternoon).
