### ISSUE TITLE
Delete Funds and Ledgers

### ISSUE THREAD

**Issue by JuleahS** [culibraries/folio#121]
When attempting to delete the pre-populated/existing Funds & Ledgers in the sandbox, receiving an error messages that says "fund not deleted" or "ledger not deleted"

Need to understand what prevents a fund or ledger from being deleted. Are there dependencies that prevent this from occuring?

**Comment by jwfuller** [comment]
I was looking at the [docs](https://docs.folio.org/docs/acquisitions/finance/#deleting-a-fiscal-year-ledger-group-fund-or-budget-records)
> Financial structure records cannot be deleted if they have other records assigned to them
I wonder if there is a sub-record that needs to be deleted first.

**Comment by jwfuller** [comment]
Confirmed with Acquisitions that this is no longer a problem
