### ISSUE TITLE
Deploy and configure mod-inn-reach

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#128]

**Comment by steveellis** [comment]
FWIW I added it to the R2-2021 yaml and have seen the container deploy at least: https://github.com/culibraries/folio/blob/875a236e5004a16559eedd8cbc091ba6dfabce7e/pulumi/folio/deployments/R2-2021.yaml#L48

**Comment by sabetiv** [comment]
Issue is no longer valid as we are now 3rd party hosted
