### ISSUE TITLE
Organizations Data to Import/Migrate

### ISSUE THREAD

**Issue by JuleahS** [culibraries/folio#131]
Organization data needs to be determined prior to migrating Order data/records.

Organization data will be migrated via a CSV file rather than directly from Sierra to avoid migrating obsolete vendor records in Sierra. 
A spreadsheet with all the relevant fields and readily available vendor data needs to be created.
Pull username/password information for Usage, Admin, and other administrative login info from ERM records in Sierra.
Identify active order records with vendor listed as "none" and create new Sierra vendor records & codes.

**Comment by blocke1** [comment]
It looks like both the contact information from the contact records in Sierra and the admin/statistics login info from fields in the ERM record will need to go into the Organizations app in FOLIO. I will work on merging this information into one file. This next meeting free week will be a good time for me to work on this.

**Comment by jwfuller** [comment]
Organization data has been delivered to Data Migration Vendor
