### ISSUE TITLE
Fund Ledger Budget Groups Data to Import/Migrate

### ISSUE THREAD

**Issue by JuleahS** [culibraries/folio#132]
Fund, Ledger, Budget, Groups, Fiscal Year data needs to be migrated prior to Order data.
Migrate data from a CSV file
Create documentation on what the structure is and why

**Comment by JuleahS** [comment]
Status update: Draft CSV file complete. Send to Gabby

**Comment by jwfuller** [comment]
File sent to Data Migration vendor.
