### ISSUE TITLE
Provide feedback on "Support INN-Reach Only Manual Patron Blocks"

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#139]
[UXPROD-3470](https://issues.folio.org/browse/UXPROD-3470) is seeking feedback about a feature that is proposed for Morning Glory (R2 2022)

**Comment by libraryfemme** [comment]
@jwfuller - Could we add Claire to this ticket?

**Comment by jwfuller** [comment]
This seems like a well defined and useful feature to me. I can't think of anything that is missing in that area.

**Comment by libraryfemme** [comment]
I think since there could be valid reasons to restrict someone from Prospector but not from our local collections, this also seems like a useful feature to me.
