### ISSUE TITLE
Deploy LDP application and integrate with FOLIO

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#155]
We want to deploy the [LDP](https://github.com/library-data-platform/ldp) closely developed with FOLIO. There is an [Admin guide](https://github.com/library-data-platform/ldp/blob/main/doc/Admin_Guide.md) with installation instructions.

**Comment by steveellis** [comment]
Tagging @arthur-aguilera and @sabetiv since they both have been big advocates of this.

**Comment by CUSeif** [comment]
This will be deployed with our hosted instance of FOLIO.
