### ISSUE TITLE
Work out branching strategy for FOLIO

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#171]
@jwfuller creating a ticket for this since I think it may warrant more discussion. Here's my understanding of what we want to do:

When code changes have been successfully deployed to production (either through pulumi up or through swapping staging with production):

- Merge to `main` any changes that are part of the work that caused a change to production. This will probably be triggered by a PR but it may not be. I may be that we just are ready to deploy what is on main which has been modified through a series of PRs.
- Tag `main` with a tag such as `<FOLIO quarterly release number>.<our release number>`.
- Do `push tag` to get it out to the remote since I believe tags have to be pushed separately.

Then whenever we need to make a change to production we:
1. Create a branch for the work.
2. Do a PR for the work.
3. Merge to main.
4. Perform steps above with new tag.

Here's what a given tag would look like: `R2-2021.r0` where `r0` is our "release" and will be incremented anytime we modify the production env.

@jwfuller does this sound right to you?

**Comment by steveellis** [comment]
The problem with this approach as I see it is as follows:

_`main` won't always be aligned with production deployable code._

Consider the following scenario:

1. I do a bugfix in a branch and that bugfix gets deployed to production. This happens through a PR and gets merged to `main`.
2. I then begin work on a branch (call it a feature branch if you want) and I deploy that feature to the scratch environment as part of that feature branch's development. I want to finish this feature branch so that the next feature branch can use its code. Maybe these feature branches are part of series (not hard to imagine). I do a PR. It gets merged to `main`.

Now `main` has two merges one which is production code and one which is a feature branch that is part of a set of features that are being worked on but which aren't ready for production. Main is no longer deployable production code. It's just a mainline of things that are "done".

Let's say things go really wrong and I need to build a new production instance.

Fine you say, your production code has a tag, just check that code out and build it. But what if I want to apply a patch to it before I do since I want to fix what is broken. I can do that in a new feature branch, and then when I'm done merge it to... where?

Not `main` because `main` now has both production and development code in it. In other words, if I merge this production hotfix into main and expect to tag it as `r2` and have it represent the code which is running in prod, it simply wont since main has unreleased features on it.

**So I don't think our above branching strategy is quite right for what we're trying to accomplish.**

The good news is that stock gitflow should work perfectly for what we want to do. It does this by having two branch lines: one for dev and one for production. It sounds complicated, but when you use the gitflow plugin to create and close branches, it's actually quite easy and hard to screw up.

This is what we're groping toward with our ideas for a scratch/test env and a prod env. We just need our branching strategy to be in agreement with it.

With this approach we can indeed have a branch that always represents production where you can apply production hotfixes and another one where we can do development. In my experience it's pretty clear when something falls into either category. You know when you have a hotfix (that goes to production) and you know when you have a feature (that goes into develop). 

But wait you say, gitflow is a legacy idea, can't we be more agile and do trunk based development, which is supposed to be a best practice?

I think we _could_ if we had two repos, one for say Iris and one for Kiwi. Then main could be continuously deployed. But a lot of this has to do with the reality of what we're dealing with. We're going to have very separate dev and production environments because of the nature of FOLIO.

With that in mind maybe we simply have a flower branches. But i'm not sure how that would work in practice.

I'm open to other ideas. These are just today's thoughts.

**Comment by jwfuller** [comment]
@steveellis Straight gitflow is fine with me. I don't think we want to get too complicated with only two committers

**Comment by jwfuller** [comment]
I also like basing our tags off FOLIO. So `year`.`release-for-the-year`.`our-version`. So `2021.r1.3` is our third build of infra for Iris and `2021.r3.0` would be our first build for Kiwi

**Comment by jwfuller** [comment]
@steveellis and I discussed. Going full GitFlow and tagging like `calendar-year.folio-release-for-the-year.cu-version`

**Comment by jwfuller** [comment]
Main branch with tags, tags are the things that are deployed. Feature branches for new work.
