### ISSUE TITLE
Mark item as missing

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#179]
Used when pulling holds or checking the shelves for an item that should be available but is not.

## Functionality needed

- [x] View item record and change status to missing.
- [ ] This should also record the date when the item was marked missing to enable staff to pull reports on currently missing items.

## Steps in FOLIO

It seems like this can only be done with checked out items at present

1. App: Inventory
2. Enter item identifier (barcode, title, etc) in search box
3. Click on item to open a new pane
4. In new pane, open the relevant holding and click on the item to open new window
5. In the "actions" drop down menu, select "mark as missing"
6. The date can be recorded by adding an item note using the "edit" function in the "action" drop down on the item

## Open Questions

- [ ] How do we deal with items that where checked in but their current location is mystery?

**Comment by Jema5367** [comment]
@jwfuller this one is gtg!
