### ISSUE TITLE
Schedule Search Box Change for Web Express

### ISSUE THREAD

**Issue by nleboeuftrujillo** [culibraries/folio#180]
**Requested changes for cu-libraries-search-large and cu-libraries-search-small blocks**

- [ ] Update form to point to https://discovery.ebsco.com/c/3czfwv/results?acr_values=guest&q=

this may be updated by @nleboeuftrujillo pending vendor updates

- [ ]  Add label (legend, i think?) on top of text input field,

OneSearch: find articles, books and more
 
- [ ] Update input placeholder text to read, 'Enter keywords'
- [ ]  Remove form select option (i.e., eliminate Google Scholar)
- [ ]  Change search button color to WebExpress Blue (#0377BD)

**Comment by crmcdonald** [comment]
Scheduled for 9am 6/20 per Kevin Crafts email of February 28

**Comment by crmcdonald** [comment]
Requested changes for cu-libraries-search-large and cu-libraries-search-small blocks

- [ ] Update form to point to https://discovery.ebsco.com/c/3czfwv/results?acr_values=guest&q=
this may be updated by @nleboeuftrujillo pending vendor updates
- [ ] Add label (legend, i think?) on top of text input field, 
OneSearch: find articles, books and more
- [ ] Update input placeholder text to read, 'Enter keywords'
- [ ] Remove form select option (i.e., eliminate Google Scholar)
- [ ] Change search button color to WebExpress Blue (#0377BD)
