### ISSUE TITLE
Disallow lending of specific items with missing pieces

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#187]
## Functionality needed

- [x] Change field(s) on many item records with one input and click. 
- [ ] This would also require the generation and storage of lists as in Sierra’s Create Lists function.
- [ ] Use: some items may lose functionality 
- [ ] Note that this will need a report query written eventually

## Steps

- [x] This might be locked behind cataloging functionality. The only way we might be able to do this is to mark the item as unavailable

**Comment by Jema5367** [comment]
Steps in Folio:

1. Missing pieces should be noted in the "item notes" 
2. App: Inventory
3. Enter item identifier (barcode, title, etc) in the search box
4. Click on item to open a new pane
5. Click on "holdings" and select the item to open new window
6. In the "actions" drop down menu select "edit"
7. In the "item notes" section click "item notes" and identify what items are missing.
8. Click "save and close"
9. In the "actions" drop down menu click "mark as unavailable"

**Comment by Jema5367** [comment]
@jwfuller this one is gtg!
