### ISSUE TITLE
Develop and implement a FOLIO deployment strategy

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#200]
In principle we agree on the following:

**Any and all changes made to infrastructure should be made first to a staging (non user facing) environment and tested on that environment. Once testing is complete, deployment of these changes should simply be a matter of swapping the domain of staging with production.**

This means that staging is always the last production environment, at least until staging is updated with a new build or changes of its own.

This ticket is about documenting the barriers to or work to be done to get to this arrangement.

So far I've identified a few things to work out:
* Building and deploying multiple stripes containers such that urls can be swapped without downtime.
* Updating email settings to allow for password reset.

**Comment by steveellis** [comment]
I have been researching how others are doing blue/green deployment and managing different types of environments (dev, staging and production) in k8s.

A few things have stood out:
* Many are using k8s namespaces as a way to partition different environments. So production goes into a production namespace, etc.
* Service meshes like [istio](https://istio.io/latest/about/service-mesh/) can be used to handle a lot of what we want: enhanced observability, logging, and switching between environments via their own ingresses.

This is a little different than the way we have been thinking about our pulumi stacks being standalone deployments, each including their own infrastructure etc.

I think I may argue that a service mesh is what we would be sorely missing during bad events. The key idea is it transparently sits next to your app via sidecars, and gives you the best visibility possible into its inner-workings. That it could also help with swapping between staging and production is just icing on the cake.

It seems like it should be easy enough to [deploy istio via helm](https://aws.amazon.com/blogs/opensource/getting-started-istio-eks/) just like we deploy other things like kafka.

Istio isn't the only game in town. AWS has it's own [app mesh product](https://aws.amazon.com/app-mesh).

If we go this route a few things would happen:
1. Define a single pulumi stack and app for infrastructure.
2. Define separate application-level stacks for each "environment" namespace.

If we wanted to have the best of both worlds, maybe our sandbox has its own infrastructure.

Related #174.

**Comment by steveellis** [comment]
I think the major caveat with using k8s namespaces to partition our environments is the simple fact that resources and nodes are shared. So if something goes wrong on that level (and it will) production could easily be compromised by staging which sort of defeats the whole purpose of the blue/green paradigm.

But I do still feel that using a service mesh is something we're very much going to want to do.

**Comment by steveellis** [comment]
I think whether we share the cluster across staging, prod and potentially scratch is a major consideration affecting next steps, like #170, #175 and #206. Most of the simple examples about blue/green deployment in k8s assume you're going to share the same cluster which might be fine for testing but not real life. This [reddit post](https://www.reddit.com/r/kubernetes/comments/nzkna6/kubernetes_eks_and_running_bluegreen_clusters/) rings true to me.

> At my company, I have run into multiple occasions where I need to rebuild the entire EKS cluster to make a change (change in subnets, cluster encryption, Kubernetes version upgrade, and more). This is really difficult, and can cause major issues, and can also be especially dangerous if you deploy via terraform (as terraform can destroy and recreate under your nose).

So I have been googling on "blue/green multicluster" etc. Noticed that istio lets you

> install an Istio service mesh that spans multiple clusters

More on that [here](https://istio.io/latest/docs/setup/install/multicluster/).

**Comment by steveellis** [comment]
AWS app mesh can be deployed via pulumi: https://www.pulumi.com/registry/packages/aws/api-docs/appmesh/route/.

**Comment by steveellis** [comment]
Using ALBs appears to be the simplest way to support b/g deployments. See:
* ALBs are also used for blue green deployments: https://aws.amazon.com/blogs/aws/new-advanced-request-routing-for-aws-application-load-balancers/
* https://aws.amazon.com/blogs/devops/blue-green-deployments-with-application-load-balancer/

The ALB would be defined outside the cluster and then point to whatever cluster was in prod. It enables either canary like stuff or just a straight manual switchover. Campus DNS points to the ALB. So the ALB would not be defined in the cluster via a service or via EKS magic like we currently do. Our services providing access will need to change to a different type and the certs instead of being bound the service (like they are currently -- well at least that's the UX of it -- they're really bound to the LB) get bound to the single ALB that services multiple clusters via target groups.

Good write up of this arrangement here: https://aws.amazon.com/blogs/containers/onfidos-journey-to-a-multi-cluster-amazon-eks-architecture/

There are other ways to provide this switching ability (like Istio's approach) but this may well be the simplest way I have come across so far.

For now I think service meshes are worth considering, but only if our logging doesn't provide enough visibility into the cluster. So maybe a "phase 2" thing.

**Comment by CUSeif** [comment]
Issue is no longer valid as we are now 3rd party hosted.
