### ISSUE TITLE
Easily renew all open loans for a user

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#202]
In #176 we tested renewing single items, we want to verify and document:

- [x] Renew multiple open loans for a user
- [x] Renew all open loans for a user

## Steps in FOLIO

1. App: Users
2. Enter identifier (patron name, barcode, etc.) in search box
3. Click on patrons account to open an extra pane with their info
4. Expand the "loans" menu
5. Click "open loans," which opens a new window
6. Click box next to "item title" to select all items
7. If only certain items need renewed, only click the box next to those items
8. Click "renew"

**Comment by Jema5367** [comment]
@jwfuller this one is gtg!
