### ISSUE TITLE
Cancelling because the item is not on the shelf

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#212]
Need to create a notification template

**Comment by jwfuller** [comment]
See also #119

**Comment by Jema5367** [comment]
Steps in Folio:

1. App: Users
2. Enter identifier (name, barcode, etc) in search box
3. Click on users account to open up a new pane
4. Expand the "requests" menu in the patrons account
5. Click on "open requests" to bring up a new window
6. Click on the request that needs cancelled to open a new pane
7. Open the "actions" drop down menu and select "cancel request" 
8. Select "Item not Available" as the reason for cancellation
9. This does not mark the item as unavailable though, so this will need to be done in the item record itself

**Comment by Jema5367** [comment]
Also, new functionality that will be helpful:
Closed requests can be duplicated as new, open requests by:

1. Click "closed requests"
2. Select the appropriate request
3. In the "actions" drop down, select "duplicate"
4. Click "save & close"
