### ISSUE TITLE
Develop strategy for FOLIO flower release upgrades

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#215]
We have various tickets about upgrades we want to do, but nothing tracking our strategy or design of _how we're actually going to do upgrades_. This ticket is for that.

The sooner we start formulating our approach to this the better. Sure, all of our good plans will change once we do it, but without planning ahead we're going to make mistakes that could eventually be costly to change in our infrastructure development work now.

#### Before we begin 
1. There is enough headroom to double all modules on the nodes in every env
2. All 3 envs are equivalent/mirrored
3. Logging on all 3

#### Testing and perfecting upgrade 
1. Create a copy of the prod db
2. Link this to a running scratch env 
3. Run the upgrade process on scratch which is a mirror of prod and staging 
4. Diff v1 and v2 dbs to ensure and understand the schema changes 
5. Perfect this process 

#### Moving to prod 
1. Redirect users to a maintenance page
2. Do the upgrade on staging after hours. This will be against the production database.  
3. Flip staging with prod

#### Need for documentation

@jwfuller I spent a good amount of time trying to find some sort of FOLIO documentation for the upgrade procedure. Have you seen such a doc?

I found a handful of documents that discuss various problems and solutions to upgrades under various conditions (like when an institution has changed the FOLIO schema). For example [this](https://wiki.folio.org/plugins/servlet/mobile?contentId=65114751#content/view/65114751). But I wasn't able to find a simple doc for how upgrades are supposed to be handled. I have developed my own "folk understanding" of what they are and how they work.

**Comment by jwfuller** [comment]
https://github.com/culibraries/folio/issues/14#issuecomment-1068035831

**Comment by CUSeif** [comment]
Issue is no longer valid as we are now 3rd party hosted.
