### ISSUE TITLE
View Source, and quickMARC are not working properly for instance records

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#229]
Our theory is that it is because the records were created by the superuser yet are bound to the tenant where the superuser doesn't have an account. I should be able to log in as the superuser to verify.

If you navigate to an inventory records, using a "normal" user account and look under Administrative Data the Source is superuser. This is different from how records were created in the old sandbox, where the user doing the import was a tenant user which was created for data import.

![image](https://user-images.githubusercontent.com/104455/157904207-0f206226-c6b1-4327-9e84-aa1d9dc88050.png)

**Comment by cledvina** [comment]
When the source is MARC, the instance record may not be edited.

**Comment by jwfuller** [comment]
@cledvina I can edit the record in the older instance, did something change in the mapping?

**Comment by jwfuller** [comment]
Okay, I see that now. I was looking in the wrong place. We are still having issue with quickMARC and View Source.
![folio](https://user-images.githubusercontent.com/4621248/157917794-30abfd6b-35e3-4e3d-af4b-0f5f5dab9797.jpg)

The permissions seem to be correct

**Comment by steveellis** [comment]
@jwfuller @cledvina let me know that this is likely because the source-records haven't been loaded on the new system. He's going to do a fresh load of everything to try to get parity between the two systems (old an new).

**Comment by cledvina** [comment]
@jwfuller, @steveellis :  I loaded the source records so most if not all instances should be editable via quickMarc.  Now I think I'll load the holdings and items as well.  After that, this new system should be pretty close to the old system inventory wise.

**Comment by cledvina** [comment]
Oh wait.  I already loaded holdings and items.  So inventory should be good (for now).

**Comment by jwfuller** [comment]
Those three options are working now, thanks!
