### ISSUE TITLE
Data import is failing

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#234]
As reported by @cledvina importing records can crash inventory. Restarting the inventory deployments brings it back up, but we are seeing timeouts from postgres.

A database write operation to mod-inventory-storage appears to begin and won't often return for several minutes. This can happen with just few records being written.

The environment variable that controls the connection pool us `DB_MAXCONNECTIONS`. We currently have it set to 5. We may need to increase this.

**Comment by jwfuller** [comment]
https://github.com/culibraries/folio/issues/230 May be impacted by the same issue

**Comment by steveellis** [comment]
Applied the change and am now seeing `DB_MAXPOOLSIZE=20` in mod-inventory and mod-inventory-storage's env.

**Comment by steveellis** [comment]
This change has been deployed. Charles is still having problems with his import, however the many other errors in the logs involving timeouts are completely gone. Also, Charles' import no longer crashes inventory. The only error I now see is in mod-inventory-storage:
```
15:44:27 [] [] [] [] ERROR ?                    Unhandled exception
java.lang.IllegalArgumentException: Invalid UUID string: 
        at java.util.UUID.fromString(UUID.java:215) ~[?:?]
        at org.folio.rest.persist.PostgresClient.lambda$93(PostgresClient.java:2796) ~[mod-inventory-storage-fat.jar:?]
 <snip>
```
This argues that we had multiple errors in scope, and that some of the more critical ones have been solved.
