### ISSUE TITLE
Ensure that we can upgrade to kubernetes 1.24 (dockershim depreciation)

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#243]
FOLIO could get bit by this if we upgrade to 1.24 without making sure that eks will handle this for us.

Looking at our runtime in our current stack which uses 1.21 **we are using dockershim** (using [these instructions](https://kubernetes.io/docs/tasks/administer-cluster/migrating-from-dockershim/find-out-runtime-you-use/) to get the container runtime).

When I read about the issues [here](https://kubernetes.io/blog/2022/03/31/ready-for-dockershim-removal/) I see this statement:

> Amazon EKS, Azure AKS, and Google GKE all default to containerd now, though you should make sure they do not need updating if you have any node customizations.

Hmm ok I just created this cluster why don't I then have containerd? I don't see anywhere in my code that I'm selecting the old docker runtime.

Ok I can see why [here](https://aws.amazon.com/blogs/containers/amazon-eks-1-21-released/). In v 1.21 you have to explicitly set it to containerd.

I'm not seeing anything in pulumi's [docs](https://www.pulumi.com/registry/packages/eks/api-docs/cluster/) for setting this.

**Comment by CUSeif** [comment]
Not applicable with 3rd party hosting.
