### ISSUE TITLE
Add new ACQ Material Type Codes

### ISSUE THREAD

**Issue by JuleahS** [culibraries/folio#255]
Need these additional Material Type Codes in the dropdown menu:

Photograph ACQ
Archival collection ACQ
Artwork ACQ
Postage ACQ

**Comment by CUSeif** [comment]
Added to FOLIO as PTGACQ, ACACQ, ARTACQ, POSTACQ

**Comment by CUSeif** [comment]
added to material types list and deleted from loc.
