### ISSUE TITLE
Provision RDS instance to migrate FOLIO database into after installation

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#29]
- [ ] Extend Pulumi codebase
- [ ] Support PostgreSQL v12 if possible
- [ ] Add to VPC created as part of culibraries/folio#4
- [ ] Consider logging that can be setup as part of this deployment, likely will be worth separating into a separate issue as part of the Logging milestone

## For all issues

- [ ] Tag all resources
- [ ] Use both public and private subnets. Best practice is to run our workloads in the private subnets and deploy the load balancers into the public subnets to span for the users.

## Suggested Tags

```ini
# Tags to include with sample values
Name=folio-eks-cluster
Service=FOLIO
Environment=production
Owner=CTA
Product=FOLIO
Accounting=cubl-folio
DataClassificationCompliance=standard
```

## Resources

* [Pulumi Examples](https://github.com/pulumi/examples)
* [WordPress Site in AWS Fargate with RDS DB Backend](https://github.com/pulumi/examples/tree/master/aws-py-wordpress-fargate-rds)

**Comment by jwfuller** [comment]
Related to #31 

See also https://www.pulumi.com/docs/guides/crosswalk/kubernetes/app-services/#postgres-database

**Comment by steveellis** [comment]
Number 16 is @jwfuller's write up of [this](https://github.com/culibraries/folio-ansible/tree/feature/47).

Also potentially helpful: https://dev.to/bensooraj/accessing-amazon-rds-from-aws-eks-2pc3, although it places the RDS in its own VPC, which we probably don't need or want.

**Comment by steveellis** [comment]
Completed by https://github.com/culibraries/folio/pull/141
