### ISSUE TITLE
Provision EC2 Load Balancers (L4 and L7) to support web and dedicated protocol access

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#30]
- [ ] Extend Pulumi codebase
- [ ] Appropriate security certificates
- [ ] Target Group using nginx node port (32080 for default backend) for health checks
- [ ] L7 ELB with rules to support web connections on 80/443
- [ ] L4 ELB with rules UDP/TCP based protocols for things like Connexion and SelfCheck machines
- [ ] Consider logging that can be setup as part of this deployment, likely will be worth separating into a separate issue as part of the Logging milestone

## For all issues

- [ ] Tag all resources
- [ ] Use both public and private subnets. Best practice is to run our workloads in the private subnets and deploy the load balancers into the public subnets to span for the users.

## Suggested Tags

```ini
# Tags to include with sample values
Name=folio-eks-cluster
Service=FOLIO
Environment=production
Owner=CTA
Product=FOLIO
Accounting=cubl-folio
DataClassificationCompliance=standard
```

## Resources

* [Pulumi Docs on Load Balancers](https://www.pulumi.com/registry/packages/aws/api-docs/alb/)

**Comment by steveellis** [comment]
I think we can close this out based on the arguments provided in [the PR](https://github.com/culibraries/folio/pull/102) for issue #32. The gist of it is that we can get by with an L4 load balancer and that is created automatically for us by EKS when we create a service of type LoadBalancer. Creating the service exposes a public endpoint which we can use to access HTTP services on the cluster and test things out.

I think there will still be work to do binding that load balancer to a Route53 service and certificate and forcing 443, opeing 9000 for edge connexion etc. But we should create a ticket for that when we get further along. But I think all of that will be a lot easier than it has been in the past with this new approach.
