### ISSUE TITLE
Do we need to be concerned about Check Digits in Sierra record numbers?

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#34]
A user noticed that imported records do not include the check digit. Do we want that imported?

According to the data migration vendor:
> This is intentional.  We are stripping the check digit from the HRID since it will cause a problem matching Sierra's holdings records, which contain no check digit.

- [ ] Where are we using Bib IDs that include check numbers?
- [ ] Do we need check digit functionality going forward?
- [ ] Where do we need this information historically?
    - Redirects from Chinnok permalinks to EDS
    - CU Digital Library (LUNA) `RelationLink: University of Colorado catalog record link`
    - LibGuides

**Comment by nleboeuftrujillo** [comment]
Do you have more information on how you might do Chinook redirects to EDS?

**Comment by jwfuller** [comment]
@nleboeuftrujillo Do you mean redirecting a URL like `http://libraries.colorado.edu/record=b9009908~S3` to `https://searchbox.ebsco.com/search/?schemaId=[SOMEID]`?

**Comment by nleboeuftrujillo** [comment]
Correct. We have some Chinook links embedded [in various systems](https://docs.google.com/presentation/d/1AZE2Nds6KGuG6Fbc5xnDkv-rL9idfxYu40LgEeeo8Vk/edit#slide=id.gf343737f83_0_1) (LibGuides is the biggest one that I know of, but I know their are links in LUNA and others).  I don't know if this is possible or desirable, you might want to contact those who it most impacts.

**Comment by jwfuller** [comment]
We discussed during project management weekly meeting and concluded:

- We do not need check digits going forward
- We need to make sure that we can redirect URLs from the Sierra OPAC (which use a bib number with the check digit) to EDS
