### ISSUE TITLE
Create basic EKS cluster

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#4]
- [x] Store Pulumi state in an S3 bucket so that multiple developers can update the cluster
- [x] EKS Cluster on latest kubernetes (v1.21 as on writing)
- [x] Dedicated VPC
- [x] Dedicated IAM role for kubernetes control plane to use
- [x] Dedicated Security Group that can be used for network interfaces
- [x] Nodegroup made up of `t3.xlarge` EC2 nodes. Based on our experience allocating workloads for Iris, this node size is required. We expect to run 3 nodes initially. We should create a follow up issue to optimize our node utilization possibly with additional nodegroups or by set pod affinity/anti-affinity
- [x] Create Public and Private Subnets
- [x] Utilize AWS networking add-ons for "Amazon VPC CNI", "CoreDNS", and "kube-proxy"
- [x] Make it possible to deploy multiple environments (dev, prod, staging, etc) from the same code. Tag each resource with the current environment.
- [ ] Consider logging that can be setup as part of this deployment, may be worth separating into a separate issue as part of the Logging milestone
- [x] Determine if we should use AWS KMS kubernetes secrets encryption

## For all issues

- [x] Tag all resources
- [x] Use both public and private subnets. Best practice is to run our workloads in the private subnets and deploy the load balancers into the public subnets to span for the users.

## Suggested Tags

```ini
# Tags to include with sample values
Name=folio-eks-cluster
Service=FOLIO
Environment=production
Owner=CTA
Product=FOLIO
Accounting=cubl-folio
DataClassificationCompliance=standard
```

## Resources

* https://github.com/pulumi/examples
* https://github.com/pulumi/examples/tree/master/aws-py-eks
* https://github.com/culibraries/pulumi/tree/feature/9-no-rancher
* https://www.pulumi.com/registry/packages/aws/api-docs/eks/addon/
* https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#vpc-subnet-basics

**Comment by steveellis** [comment]
It looks like Pulumi supports using KMS to encrypt k8s secrets. See `ClusterEncryptionConfigArgs`  in the docs here: https://www.pulumi.com/registry/packages/aws/api-docs/eks/cluster/

The flow would be something like:
1. Manually create the "master key" using kms on the command line or through the console.
2. Add the master key ARN to the cluster when creating it using the API referenced above.
3. Once the cluster is running, create secrets using `kubctl create secret` or maybe using other API like pulumi to do that.
4. Refer to secrets in the normal way inside k8s in your pods.
5. All k8s secrets are encrypted.

One downside is that you have to enable the encryption support when creating the cluster for the first time. You can't add encryption later. The only path is to completely recreate the cluster.

The key has to be created in the same region as the cluster. The aws account has to have access to the customer master key (CMS).

References:
* Amazon blog post about how it works: https://aws.amazon.com/blogs/containers/using-eks-encryption-provider-support-for-defense-in-depth/
* Pulumi PR that enabled the feature: https://github.com/pulumi/pulumi-eks/pull/389

**Comment by steveellis** [comment]
@jwfuller I thought I had a solution to this but after destroying and recreating the same thing happened as the first time.

1. I run `pulumi up` and everything completes except the last `CreateNodes` step, hanging for 10s of minutes trying to complete but eventually fails with `NodeCreationFailure: Instances failed to join the kubernetes cluster`.
2. I run `pulumi up` again and it updates running the last step and immediately completes. The nodes are able to join the second time around apparently. 

So there's something about the code apparently that fails on the first pass, but succeeds on the second. The current commit has my code that I'm running. If nothing occurs to you I can ask on pulumi slack or open a ticket. The aws docs [for this error](https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html) are a bit unhelpful. After I run it a second time I'm able to access the internet from the debug container.

I'm assuming this has something to do with [how I'm creating the private subnet](https://github.com/culibraries/folio/blob/e40eed313f731b3c0b77befb6810919c4667bf1e/pulumi/folio/vpc.py#L68). That's really the only thing about my code that is substantially different from the sample code that this is based on.

**Comment by steveellis** [comment]
I'm trying various things here in the section on Nodes fail to join the cluster: https://docs.aws.amazon.com/eks/latest/userguide/troubleshooting.html

**Comment by jwfuller** [comment]
@steveellis I was looking at [Pulumi Docs for EKS Networking](https://www.pulumi.com/docs/guides/crosswalk/aws/eks/#configuring-your-eks-clusters-networking) specifically there is a line in their `eks.ClusterArgs` that reads `private_subnet_ids = vpc.private_subnet_ids,`. What do you think about trying the config in that layer rather than at the node group?
