### ISSUE TITLE
Define and script a process for exporting and importing FOLIO reference data

### ISSUE THREAD

**Issue by jwfuller** [culibraries/folio#54]
FOLIO has two types of data: Reference and Sample. Reference data is most similar to "configuration" (loan rules, permissions, item status) and sample data is most similar to "content" (instances, holdings, items). Reference data may be controlled entirely by code, both in code and by users, or only by users; may be changed by code during upgrades (replacing deleted values or creating an error if a new unique key conflicts with a user created value).

The FOLIO project is working on better ways to handle reference data during upgrades (see Resources). We need to define a process to move Reference Data between to identical instances of FOLIO. This will help us create/rec-create instances for data migration and testing.

- [ ] Runs in a container inside the cluster
- [ ] Can run export and import independently
- [ ] Can store data in S3 (not sure how this might impact the ability to manually edit the data, which would be nice to do)

## Resources

* [SysOps SIG - Upgrades with Reference data](https://wiki.folio.org/display/SYSOPS/Upgrades+with+Reference+data)
* [Tech Council - Defining data types in FOLIO for automatic upgrades](https://wiki.folio.org/display/TC/Defining+data+types+in+FOLIO+for+automatic+upgrades)
* [SysOps SIG Meeting Notes - using loadReference](https://wiki.folio.org/pages/viewpage.action?pageId=36576307)
* [Schema upgrade testing](https://wiki.folio.org/display/~marcjohnson/Marc%27s+guide+to+local+schema+upgrade+testing)
* [FOLIO Services from EBSCO](https://github.com/FOLIO-FSE)

## Code samples

- https://github.com/indexdata/folio-import/blob/master/loadRefData.js
- https://github.com/indexdata/folio-import/blob/master/downloadAllRefData.js

**Comment by sabetiv** [comment]
Issue is no longer valid as we are now 3rd party hosted
