### ISSUE TITLE
Establish a schedule for developing and offering FOLIO training

### ISSUE THREAD

**Issue by CUSeif** [culibraries/folio#58]
We need to plan training and documentation, and publish that plan. We have gotten the following questions related to training:

- [x] Are there public timelines for migration/training opportunities, etc.? 
- [x] Will in people on the pods be required to train everyone else?

People have also expressed concern that Libraries faculty/staff aren't absorbing the scope and depth of impacts on workflows and day-to-day processes. Hopefully creating a clear and public plan for the scope of the training and documentation will do some "show rather than tell".

**Comment by jwfuller** [comment]
[Timelines](https://folio-at-cu.readthedocs.io/en/latest/admin/timelines.html) show that we plan to create training from May through August and then deliver it from September to Jan 2023 and through go-live. We have considered a few models for training and may get some help from a vendor.
