### ISSUE TITLE
Kafka TimeoutException when receiving messages from inventory pods

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#60]
@jwfuller was reported by Charles. He's able to import/upsert his 50 records but the batch API also returns a gateway timeout, which at first made him think that the import hadn't succeeded.

This might be salient. The kafka host in the `kafka-connect` secret is `kafka.kafka-iris.svc.cluster.local`. Is that still valid now that I have 1 pod? I'm fairly sure this is related to the fix I made for issue #3 (dialing down kafka to one pod).

The error messages in mod-inventory-storage are like this:

```
org.apache.kafka.common.errors.TimeoutException: Expiring 9 record(s) for folio.culibraries.inventory.holdings-record-0:120005 ms has passed since batch creation
21:55:12 [] [] [] [] ERROR DomainEventPublisher Unable to send domain event [4f3fc5e6-bc6e-55f4-b931-d444860f8a84], payload - [org.folio.services.domainevent.DomainEvent@43dc030a[oldEntity=org.folio.rest.jaxrs.model.HoldingsRecord@74c483fb,newEntity=org.folio.rest.jaxrs.model.HoldingsRecord@559a984a,type=UPDATE,tenant=culibraries]]
```

I believe this is the exact same message we saw yesterday in issue #1. My theory is that it is timing out because it can't send the message to kafka. Kafka has nothing to say in its logs which implies that mod-inventory-storage can't reach the host.

Another error that also appears 50 times is this:
```
21:34:39 [] [] [] [] WARN  ?                    Backend notice: severity='NOTICE', code='23F09', message='Cannot update record 4753d25f-9a24-5016-a8f8-c45e98e94d96 because it has been changed: Stored _version is 3, _version of request is 1', detail='null', hint='null', position='null', internalPosition='null', internalQuery='null', where='PL/pgSQL function instance_set_ol_version() line 8 at RAISE', file='pl_exec.c', line='3862', routine='exec_stmt_raise', schema='null', table='null', column='null', dataType='null', constraint='null'
```
Which very much looks like an optimistic locking error from postgres (it says so much `ol_version`) but I thought OL is a future feature, not something in the current release. The OL code makes heavy use of this `_version` property.

**Comment by jwfuller** [comment]
This has been temporarily resolved via the work in https://github.com/culibraries/folio/issues/2#issuecomment-963518678. ID has tested and confirmed that a batch load works.

**Comment by steveellis** [comment]
Noticing that both of Charles' reports involve 504 errors-- his latest report on Saturday and the one referenced here.

Theory: All of our cluster performance problems are these timeout errors￼. When we're testing in the browser it may somewhat masked but it's the same problem￼. Sometimes a search succeeds, sometimes not so much because the gateway is timing out.

In our case the gateway is ELB and EKS.

https://aws.amazon.com/premiumsupport/knowledge-center/eks-http-504-errors/
