### ISSUE TITLE
Permission sets for ILL staff and ILL students

### ISSUE THREAD

**Issue by libraryfemme** [culibraries/folio#61]
There may be a need to assign several batches of permissions to both ILL staff and students. This is because in ILL we need to perform basic cataloging functions ("fast add") as well as patron account interactions.

Probably best to check what Sierra permissions my account has ("levrault"), and make a comprehensive list from that. Major functions shown below.

Create brief and item records; 2) Delete bib and item records; 3) Place holds in Sierra and INN-Reach under patron accounts and other libraries' accounts, 4) Check items in and out; 5) Renew items.

**Comment by jwfuller** [comment]
@libraryfemme You have the following permission sets: `Cataloger - General`, `Circulation - General`, `Circulation - Manager`. The sets are in a [Google Sheet](https://docs.google.com/spreadsheets/d/119vE_FiWx0Aupb7lPqNWeUsWN0pJZdP_qSKMRZAF0Nk/edit#gid=0).

I am guessing that we will get rid of the `Manager` set at the very least.

**Comment by CUSeif** [comment]
@libraryfemme - do all folks in the ILL unit have/need the same permissions? I'm working on creating the general permission set and need to know if there are differences between your, another staff member, and a student in terms of what they actually need (do students create order records for instance?)

**Comment by libraryfemme** [comment]
@CUSeif All the staff have the same permissions. The students do have fewer permissions. All students log in using Username: yyillcirc in Sierra. They do not create order records.

**Comment by CUSeif** [comment]
@libraryfemme I've created an ILL General and ILL Staff permission set in FOLIO. General includes permissions typical ILL use. Staff have additional permissions for creating catalogue records and orders. Staff would have both permission sets assigned, students only the general. Let me know if you'd like to meet to review/test these so we can close the issue.

**Comment by CUSeif** [comment]
The student accounts have

Inventory: View instances, holdings, and items
Inventory: View, create holdings
Inventory: View, create items
Inventory: View, create, edit holdings
Inventory: View, create, edit items
Inventory: View, create, edit, delete holdings
Inventory: View, create, edit, delete items

permissions.

**Comment by libraryfemme** [comment]
Lending needs to be able to check items in/out, including inn-reach items when available. They also need to be able to add notes to the item record. *Partially resolved in conjunction with @CUSeif today, except inn-reach.

Borrowing needs to be able to delete instances. Hoping the Inventory app demo will answer this question.

**Comment by jwfuller** [comment]
@libraryfemme There is not a way to delete instances at this time. See #64

**Comment by libraryfemme** [comment]
@CUSeif - I think we can close this ticket as soon as you confirm that student assistants are able to add notes to item records.

**Comment by CUSeif** [comment]
Permissions to add notes have been added.
