### ISSUE TITLE
Create permission set(s) for Courses

### ISSUE THREAD

**Issue by katallm** [culibraries/folio#62]
Determine: 

- [ ] how many levels/sets of permissions are needed for Courses?
- [ ] which permissions should be included
- [ ] who should be assigned these permission sets

**Comment by katallm** [comment]
Taking the following to the RA pod for review. Proposing the following sets: 

- Reserves - General (should include Courses: Add and edit courses' reserved items; Courses: Read, add, and edit courses
- Reserves - Manager (should include Courses: Add, edit, and remove courses' reserved items; Courses: Read, add, edit, and delete courses)

Staff who do not work directly with course reserves do not need most Courses permissions. So that all users can view information about course reserves, the "Courses: Read all" permission should be part of the "view all" permission set for all staff once that is created. 

Propose that 1 or 2 staff are designated as having the Courses Manager permission set - primarily the Reserves Specialist, Amber Thompson. These general/manager sets retain editing access for all of those who need it but restricts access to the ability to delete reserve items and courses.

**Comment by CUSeif** [comment]
Created these sets with the permissions listed above.

**Comment by jwfuller** [comment]
@CUSeif Will check the permissions for the `Reserves - General` set

**Comment by CUSeif** [comment]
All members of the RA Pod that have an active FOLIO account have at least the general level of Reserve permission set applied to their account.

**Comment by katallm** [comment]
I'm still not able to add or edit courses. I logged out and back in, is there anything else I need to do?

**Comment by jwfuller** [comment]
Now set in both environments.
