### ISSUE TITLE
Prepare FOLIO for larger data loads during data migration 

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#66]
@jwfuller looking at Jason Root's checklist that he shared on the slack kubernetes channel. Think there's a lot of useful stuff here. Beefing up the inventory modules makes sense and argues for more headroom in the cluster. Seems relevant in light of #60.

> These are the container settings we are using in Honeysuckle environments to support data import loads of 5000 records. Note that as of Honeysuckle, my understanding is that data import files any larger than that are not supported, and in fact I think the recommendation from the development team was more like 3000 records in a file -- but we found we could push it to 5000 with these settings.
> 
> Our approach is, I think, much more conservative than Jason's "just triple it all" 
>  (not to say that's not valid!)
> 
> mod-inventory: 3 replicas, memory limit of 1342177280 (default is 715827883)
> mod-inventory-storage: 3 replicas
> mod-pubsub: memory limit of 2684354560 (default is 1073741824)
> mod-source-record-manager: 3 replicas
> mod-source-record-storage: 3 replicas, memory limit of 1073741824 (default is 603725575)
> 
> For all other modules, we are running with 1 replica and the default memory allocation. We do not have CPU limits set (and have so far not seen modules run away with CPU) -- in our experience memory consumption is the primary driver for needing to increase the size of our worker node pool, not compute.
> 
> You may ask, "why just one replica as a rule?" I think that's a reasonable question. Our experience is that when a module "goes down," it more often than not hangs rather than dying, and so does not get restarted. If the module is clustered, that can make diagnosis of a problem harder, as the unresponsive module instance may be masked by the other live instances. Of course you can change the behavior of the container orchestration system to institute API-specific liveness probes and restart a module instance when it becomes unresponsive, but our current strategy is to prioritize capturing a module in an unresponsive state in order to troubleshoot and file a bug over just keeping the system up and running. I expect as FOLIO matures we will change that priority.
> 

> All the things to be sure are set and done before we migrate:
> 
> 1.) All modules and DBs spun down
> 2.) Okapi DB cleared, okapi_modules DB cleared, Kafka DB cleared
> 3.) DBs spun up
> 4.) Edit Folio DB postgresql.conf to increase max worker processes, effective cache size and max wal size
> 5.) All modules and Okapi spun up except mod-data-migration, mod-ldp, LDP crons, and mod-spine-o-matic
> 6.) Tamu and Diku tenants created
> 7.) Tamu and Diku module deployment for tenants
> 8.) tamu_admin, backup_admin and diku_admin superusers created
> 9.) Tenant admin passwords changed
> 10.) System Admin user groups created and tenant admin users assigned
> 11.) Diku tenant locations/institutions and etc removed from Tamu instance
> 12.) All Permissions set created with all perms visible and hidden (except SYS and most Okapi perms) and assigned to tenant admin users
> 13.) Usernames, emails, patron group assignments, removal of service points - all updated for tenant admin users and Folio "system users"
> 14.) Set tenant timezone and plugins
> 15.) mod-circulation-notimers enabled for Tamu tenant
> 16.) Backup Folio modules DB for easy roll-back
> 17.) Okapi and Folio modules scaled out to 5 for those APIs being heavily utilized during the migration
> 
> Post Migration:
> 
> 1.) Set back DB max wal size and timeout to 4GB and 5min respectively, set work/temp/maint mem levels back to 128MB
> 2.) Create the edge user - assign migrated edgeuser perm set
> 3.) Create the vufind user - assign migrated vufind perm set
> 4.) Deploy K8s Job to create tenant configs for Folio email system and self-checkout
> 5.) Re-enable mod-circulation with timers
> 6.) Spin back up mod-spine-o-matic
> 7.) Un-suspend Divit import users, LDP data update and age-to-lost K8s crons
> 8.) Check and set tenant timezone and plugin settings
> 9.) Enable SSO for tamu tenant
> 10.) Scale backend modules to normal levels
> 11.) Create and re-index Elastic Search for the mod-search instances
> 12.) Run https://github.com/folio-org/mod-inventory-storage/blob/master/src/main/resources/templates/db_scripts/populatePublicationPeriod.sql from within DB

**Comment by jwfuller** [comment]
See also https://github.com/culibraries/folio/issues/2#issuecomment-963518678

**Comment by steveellis** [comment]
See this as well: https://wiki.folio.org/pages/viewpage.action?pageId=79471347

**Comment by steveellis** [comment]
Looking at the current https://lib-rancher.colorado.edu/ instance, this is the module pod instance count:

* mod-inventory 1
* mod-inventory-storage 2
* mod-source-record-storage 2
* mod-source-record-manager 2

**Comment by jwfuller** [comment]
I think we where running 3 inventory pods but scaled down to one to try and diagnosis the issue with searching.

**Comment by steveellis** [comment]
Closing out with #161. @jwfuller note that I am currently scaling pods manually with `kubectl scale deployment <DEPLOYMENT NAME> --replicas=<#PODS>` until we have a better feel for what kind of scaling params we want. Maybe we should always do it this way. It's painless and appears to survive pulumi redeploying the containers. In any case it is analogous to what we were doing with rancher without the rancher hassle.
