### ISSUE TITLE
Document delivery/request a PDF links in EDS

### ISSUE THREAD

**Issue by libraryfemme** [culibraries/folio#67]
ILL offers a service for its print/physical items where CU patrons can request that a PDF scan be made of various portions of the content, usually articles or book chapters. Embedded in Chinook records for eligible items are request buttons that open ILLiad so that a user can make such a request.

These links should be easy to set up because they only open ILLiad - they do not accomplish anything else (sadly). They don't even open a specific request form in ILLiad - they just go to its main page. I am not sure if EDS has more functionality that would enable some of the information from the actual record to be passed through to ILLiad.

Example in Chinook:

Journal of personality and social psychology
http://libraries.colorado.edu/record=b1277666~S3
Link in record: Request a PDF (UCB only)

Has data migration impact. Need to make sure the link migrates from checking to instance holdings

**Comment by CUSeif** [comment]
A very quick search of what documentation EDS has, it appears that the service can provide OpenURLs which can be configured so that whatever info can be transferred to the specific ILLiad form that needs to have info provided rather than having to have the patron complete the form.

**Comment by nleboeuftrujillo** [comment]
Beth, is the user story for this feature this? As a faculty member, I'd like to know I can get a specific article emailed to me in print (rather then having to request a full journal volume), so that I can use the article. 

For EDS, we might be able to do this without using the link in the checkin record and therefor would not need to import it over. I would add the serials subpod to this discussion or the metadata pod as I know I've discussed this with Emily and Melanie.  

Another question; can we even import that link into FOLIO? If the answer is No then that would help eliminate some extra work for metadata.

**Comment by libraryfemme** [comment]
> Beth, is the user story for this feature this? As a faculty member, I'd like to know I can get a specific article emailed to me in print (rather then having to request a full journal volume), so that I can use the article.
> 
> For EDS, we might be able to do this without using the link in the checkin record and therefor would not need to import it over. I would add the serials subpod to this discussion or the metadata pod as I know I've discussed this with Emily and Melanie.
> 
> Another question; can we even import that link into FOLIO? If the answer is No then that would help eliminate some extra work for metadata.

The user story is more like: I would like to request a PDF of something that the library holds in print or hardcopy format so that I don't have to request the print item and create the PDF myself. This service is for any patron who can access ILLiad, and is not limited to faculty.

I don't know if we can do this w/o the link in the checkin record, nor do I know if we can even import that link into FOLIO. @esemenoff - do you know?

**Comment by nleboeuftrujillo** [comment]
Honestly we could probably use EDS link logic to attach different ILLiad forms to different format types. For example, for all physical books you could have a link that says something like "Request a PDF of a Chapter (1-2 days delivery)" that links to a customized Illiad form. Would that be something worth investigating? We would not have to use the 856 link if we can make the logic work, and the form would be prefilled.

**Comment by esemenoff** [comment]
That does sound like something worth investigating. I haven't explored using urls in FOLIO yet, so couldn't say how 856 links are going to import, or what they're going to look like.

**Comment by libraryfemme** [comment]
Test record: will be TN 1099055 (for user stories.)

**Comment by jwfuller** [comment]
Spoke with @libraryfemme, this appears to be complete.
