### ISSUE TITLE
Material Types for Acquisitions on PO Lines

### ISSUE THREAD

**Issue by JuleahS** [culibraries/folio#73]
In Sierra Acquisitions has specific format codes to define the format/material type of what is being purchased. In FOLIO the Material Type field is used on the PO Line for this purpose. Because the Material Type is being derived from the item type, some of these codes are not equivalent or do not encompass what we purchase. Michigan State included a prefix of "ACQ" for material types to be used by Acquisitions only. Sometimes this duplicated existing materials types. For example: "ACQ print book."

Acquisitions does need some unique materials types for resources we purchase that would not have an instance/item record. 

Should Acquisitions use a hybrid approach of using the shared Material Type codes + have unique codes with ACQ prefix, or should we have our own ACQ prefix codes?

**Comment by jwfuller** [comment]
@JuleahS Is going to take a look at the list from #26 and we will address any additional needs via prefixed types

**Comment by jwfuller** [comment]
Need to mesh the new tab in the [Google Sheet](https://docs.google.com/spreadsheets/d/1mvbuoJtqABP5Bu_RL-sQNM2q24fovA8Q3WYin4dSKj8/edit#gid=542401615) with the main list (using a prefix if it is a type specific to Acquisitions)

**Comment by CUSeif** [comment]
@JuleahS I've added preliminary codes to your tab on the sheet. Do you think ACQ item or item type ACQ would be preferred by your group?

**Comment by JuleahS** [comment]
> 

I changed a few of the codes to clarify what they are or to avoid confusion with other types of content

**Comment by JuleahS** [comment]
> > 
> 
> I changed a few of the codes to clarify what they are or to avoid confusion with other types of content

Also, I'm not sure what you mean by "ACQ item type" or "item type ACQ"? Do you mean prefix versus suffix?

**Comment by CUSeif** [comment]
_Do you mean prefix versus suffix?_ 

Yes. Prefix they'd all be at top of list. Suffix they're in line with typical item types

**Comment by JuleahS** [comment]
Let's try the suffix approach. I think having the item types mixed in with other item types might be more user friendly.

**Comment by CUSeif** [comment]
I've added the item types as requested.

**Comment by jwfuller** [comment]
@JuleahS Do you need any additional Item Types?

**Comment by jwfuller** [comment]
We will open a follow up issue if more Item Types are needed.
