### ISSUE TITLE
Investigate 504 gateway timeout as cause of our cluster performance problems

### ISSUE THREAD

**Issue by steveellis** [culibraries/folio#91]
See https://github.com/culibraries/folio/issues/60#issuecomment-968422735

I think it is possible to describe everything that we have encountered with this latest round of performance problems as timeout-related. It could be that we just need to make some adjustments to k8s/eks settings that affect that.

cc @jwfuller

**Comment by steveellis** [comment]
I recall seeing some discussion on teams with Mark about this making adjustments to timeouts so maybe these tweaks have already been tried. But Charles second error report on Saturday got me thinking about this.

**Comment by jwfuller** [comment]
See line 5 in the list on https://github.com/culibraries/folio/issues/2#issuecomment-963518678. One timeout has been increased
