### ISSUE TITLE
EDS Database Questionnaire submitted

### ISSUE THREAD

**Issue by nleboeuftrujillo** [culibraries/folio#93]
To show our resources in EDS, Publication Finder, and Full Text Finder (which will eventually run BrowZine and connect to Google Scholar, et al.), we will need to have the EDS Holdings and EDS Index collections activated, configured, and tested. This will probably be done as part of the [Issue 89 workflow](https://github.com/culibraries/folio/issues/89).

- [x] [EDS Partner Database Questionnaire](https://docs.google.com/document/d/1axhp6uoJ0MYWd0yHregUUg3Ufhjmei5LojJ0LJX8wvI/edit#heading=h.9vgrybpr5lxu), questions for Dec 14 meeting put in, known values filled out
- [x] Questionnaire done and submitted by Steve Brown

**Comment by jwfuller** [comment]
Blocks #88
